"""initial migration

Revision ID: 0adf04f347fb
Revises: 3ebfd9c4e093
Create Date: 2017-01-20 19:20:57.143149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0adf04f347fb'
down_revision = '3ebfd9c4e093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Flaskroles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('Flaskroles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Flaskroles_default'), 'Flaskroles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Flaskroles_default'), table_name='Flaskroles')
    op.drop_column('Flaskroles', 'permissions')
    op.drop_column('Flaskroles', 'default')
    # ### end Alembic commands ###
