"""initial migrgration

Revision ID: 0b9be1182785
Revises: 6187a5080cd9
Create Date: 2017-01-20 20:25:05.891447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9be1182785'
down_revision = '6187a5080cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Flaskusers', 'last_login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Flaskusers', sa.Column('last_login', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
