"""initial migrations

Revision ID: 228e062bd617
Revises: b882e24193bb
Create Date: 2017-02-12 14:47:03.933876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228e062bd617'
down_revision = 'b882e24193bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Flaskusers', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Flaskusers', 'confirmed')
    # ### end Alembic commands ###
