"""initial migration

Revision ID: b882e24193bb
Revises: 51e96a6887a9
Create Date: 2017-02-08 20:37:44.268182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b882e24193bb'
down_revision = '51e96a6887a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Flaskusers_location', table_name='Flaskusers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Flaskusers_location', 'Flaskusers', ['location'], unique=1)
    # ### end Alembic commands ###
