"""initial migrgration

Revision ID: d2ad01905605
Revises: 528f045d92d9
Create Date: 2017-02-01 20:35:20.252501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ad01905605'
down_revision = '528f045d92d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Flaskusers', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Flaskusers', 'last_login')
    # ### end Alembic commands ###
